# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YouVideo
  pod 'XCDYouTubeKit', '~> 2.5'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'YouVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'YouVideo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YouVideo-tvOS

  target 'YouVideo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
